_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 77
            "2":
                - 1
                - 5
                - 41
                - 53
                - 77
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": darwin-x86_64
batch_size:
    value: 32
benchmark:
    value: gnn
dataset:
    value: beth
hidden_size:
    value: 64
learning_rate:
    value: 0.001
num_layers:
    value: 3
seed:
    value: 1
